server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d702qmgvqt3b6rpk0-a:5432/homevalue
spring.datasource.username=homevalue_user
spring.datasource.password=IZnic2eyWcIBbscfunnqZnLu65BcyR7v
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true